module GithubHelpers
  def repository_response
    <<-RESP
    {
      "total_count": 40,
      "incomplete_results": false,
      "items": [
        {
                "id": 12014401,
                "name": "Tetris",
                "full_name": "PSNB92/Tetris",
                "owner": {
                    "login": "PSNB92",
                    "id": 5201002,
                    "avatar_url": "https://avatars2.githubusercontent.com/u/5201002?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/PSNB92",
                    "html_url": "https://github.com/PSNB92",
                    "followers_url": "https://api.github.com/users/PSNB92/followers",
                    "following_url": "https://api.github.com/users/PSNB92/following{/other_user}",
                    "gists_url": "https://api.github.com/users/PSNB92/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/PSNB92/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/PSNB92/subscriptions",
                    "organizations_url": "https://api.github.com/users/PSNB92/orgs",
                    "repos_url": "https://api.github.com/users/PSNB92/repos",
                    "events_url": "https://api.github.com/users/PSNB92/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/PSNB92/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "private": false,
                "html_url": "https://github.com/PSNB92/Tetris",
                "description": "Tetris Project",
                "fork": false,
                "url": "https://api.github.com/repos/PSNB92/Tetris",
                "forks_url": "https://api.github.com/repos/PSNB92/Tetris/forks",
                "keys_url": "https://api.github.com/repos/PSNB92/Tetris/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/PSNB92/Tetris/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/PSNB92/Tetris/teams",
                "hooks_url": "https://api.github.com/repos/PSNB92/Tetris/hooks",
                "issue_events_url": "https://api.github.com/repos/PSNB92/Tetris/issues/events{/number}",
                "events_url": "https://api.github.com/repos/PSNB92/Tetris/events",
                "assignees_url": "https://api.github.com/repos/PSNB92/Tetris/assignees{/user}",
                "branches_url": "https://api.github.com/repos/PSNB92/Tetris/branches{/branch}",
                "tags_url": "https://api.github.com/repos/PSNB92/Tetris/tags",
                "blobs_url": "https://api.github.com/repos/PSNB92/Tetris/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/PSNB92/Tetris/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/PSNB92/Tetris/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/PSNB92/Tetris/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/PSNB92/Tetris/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/PSNB92/Tetris/languages",
                "stargazers_url": "https://api.github.com/repos/PSNB92/Tetris/stargazers",
                "contributors_url": "https://api.github.com/repos/PSNB92/Tetris/contributors",
                "subscribers_url": "https://api.github.com/repos/PSNB92/Tetris/subscribers",
                "subscription_url": "https://api.github.com/repos/PSNB92/Tetris/subscription",
                "commits_url": "https://api.github.com/repos/PSNB92/Tetris/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/PSNB92/Tetris/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/PSNB92/Tetris/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/PSNB92/Tetris/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/PSNB92/Tetris/contents/{+path}",
                "compare_url": "https://api.github.com/repos/PSNB92/Tetris/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/PSNB92/Tetris/merges",
                "archive_url": "https://api.github.com/repos/PSNB92/Tetris/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/PSNB92/Tetris/downloads",
                "issues_url": "https://api.github.com/repos/PSNB92/Tetris/issues{/number}",
                "pulls_url": "https://api.github.com/repos/PSNB92/Tetris/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/PSNB92/Tetris/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/PSNB92/Tetris/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/PSNB92/Tetris/labels{/name}",
                "releases_url": "https://api.github.com/repos/PSNB92/Tetris/releases{/id}",
                "deployments_url": "https://api.github.com/repos/PSNB92/Tetris/deployments",
                "created_at": "2013-08-10T02:35:52Z",
                "updated_at": "2017-09-06T11:38:22Z",
                "pushed_at": "2016-11-19T10:13:42Z",
                "git_url": "git://github.com/PSNB92/Tetris.git",
                "ssh_url": "git@github.com:PSNB92/Tetris.git",
                "clone_url": "https://github.com/PSNB92/Tetris.git",
                "svn_url": "https://github.com/PSNB92/Tetris",
                "homepage": null,
                "size": 135,
                "stargazers_count": 28,
                "watchers_count": 28,
                "language": "Java",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "forks_count": 50,
                "mirror_url": null,
                "open_issues_count": 1,
                "forks": 50,
                "open_issues": 1,
                "watchers": 28,
                "default_branch": "master",
                "score": 60.607033
            }
      ]
    }
    RESP
  end
end
